# Generated by Django 5.1.3 on 2024-11-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.FloatField(default=0),
        ),
    ]
