# Generated by Django 5.1.3 on 2024-11-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solve_url',
            field=models.URLField(default=''),
        ),
    ]
