# Generated by Django 5.1.3 on 2024-11-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_solve_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='solve_url',
            field=models.TextField(default=''),
        ),
    ]
