# Generated by Django 5.1.3 on 2024-11-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_solve_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_url',
            field=models.URLField(null=True),
        ),
    ]
