# Generated by Django 5.1.3 on 2024-11-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_body_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
