# Generated by Django 5.1.3 on 2024-11-23 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_title_alter_post_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=3417, on_delete=django.db.models.deletion.CASCADE, to='posts.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(default=611, on_delete=django.db.models.deletion.CASCADE, to='posts.section'),
        ),
    ]
