# Generated by Django 5.1.3 on 2024-11-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_topic_alter_topic_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='value',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default=388, on_delete=django.db.models.deletion.CASCADE, to='posts.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='section',
            field=models.ForeignKey(default=9673, on_delete=django.db.models.deletion.CASCADE, to='posts.section'),
        ),
    ]
